version: "3.3"
services:

  mysql-db:
    image: mysql:5.7
   
    container_name: mysql-db
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: php-my-admin
    env_file: ./.env
    ports:
      - $PHPMYADMIN_PORT:80
    environment:
      PMA_HOST: mysql-db

  springboot-be:
    depends_on:
      - mysql-db
    image: kchouk/examen:latest
    container_name: springboot-be
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure

volumes:
  db:
